version: '3.4'
services:
    seq:
        container_name: seq-dev
        hostname: seq-dev-host
        image: datalust/seq:latest
        volumes:
            - seq_data:/data
        environment:
            - ACCEPT_EULA=Y
        ports:
            - 5351:5341
            - 8051:80
            
    rabbit:
        container_name: rabbit-dev
        hostname: rabbit-dev-host
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
        volumes:
            - rabbit_data:/var/lib/rabbitmq
            - rabbit_logs:/var/log/rabbitmq
            - ./rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
            - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
        ports:
            - 5682:5672
            - 15682:15672

volumes:
    rabbit_data:
        name: dev-rabbit_data
    rabbit_logs:
        name: dev-rabbit_logs
    seq_data:
        name: dev-seq_data

networks:
  default:



