version: '3.4'
services:
    seq:
        container_name: seq-dev
        hostname: seq-dev-host
        image: datalust/seq:latest
        volumes:
            - seq_data:/data
        environment:
            - ACCEPT_EULA=Y
        ports:
            - 5351:5341
            - 8051:80

    redis:
        container_name: redis-dev
        hostname: redis-dev-host
        image: redis
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - 6389:6379
            
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment: 
            - REDIS_HOSTS=local:redis:6379
        ports: 
            - 8082:8081

volumes:
    seq_data:
        name: dev-seq_data
    redis_data:
        name: dev-redis_data

networks:
  default:



