name: Master Build & Publish

on:
  push:
    branches: 
    - master
    - develop
    paths:
    - 'Examples/Source/**'

jobs:
  build:
    env:
      buildVersion: '6.0.${{github.run_number}}'
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - name: Build All Example Solutions
      working-directory: ./Examples/Source
      run: ./build-examples.sh
